apiKey: "yourKey"
videoTitle: "My great server ad"

ranks:
  vip:
    subs: "10-249"
    commands:
    - "lp %player% parent add vip"
    - "say %player% got a VIP rank for an ad!"
  yt:
    subs: "250-999"
    commands:
    - "lp %player% parent add yt"
    - "say %player% got a YT rank for an ad!"
  ytplus:
    subs: "1000-*"
    commands:
    - "lp %player% parent add ytplus"
    - "say %player% got a YT+ rank for an ad!"

messages:
  notForConsole: "&7&l[YoutubeRank] &cThis command can only be run by an online player"
  noPermission: "&7&l[YoutubeRank] &cYou don't have permission to do that"
  correctUsage:
  - "&7&l[YoutubeRank] &cCorrect usage: /yt <videoLink>"
  - "&7&l[YoutubeRank] &cTo learn more - use &7/ytinfo &ccommand"
  reloadCompleted: "&7&l[YoutubeRank] &aConfig reload completed"
  startingRequest: "&7&l[YoutubeRank] &aRequesting YouTube API..."
  videoAlreadyUsed: "&7&l[YoutubeRank] &cThis video was already used"
  channelAlreadyUsed: "&7&l[YoutubeRank] &cThis channel was already used"
  wrongUrl: "&7&l[YoutubeRank] &cThis is not a valid YouTube video link"
  wrongTitle: "&7&l[YoutubeRank] &cYour video must have a title: &7%title%"
  videoGetFailed: "&7&l[YoutubeRank] &cFailed to get video data"
  channelGetFailed: "&7&l[YoutubeRank] &cFailed to get channel data"
  subCountHidden: "&7&l[YoutubeRank] &cYour sub count cannot be hidden"
  minSubs: "&7&l[YoutubeRank] &cYou must have at least %subs% subs to get a rank"
  noRankSetting: "&7&l[YoutubeRank] &cNo rank settings set for your sub count, please contact an admin"