name: YoutubeRank
version: @version@
main: kamilki.me.youtuberank.YoutubeRank
authors: [Kamilkime]
description: Give your players a rank for sharing the server video ad
website: https://github.com/Kamilkime/YoutubeRank

commands:
  youtube:
    description: "Submit your ad video"
    aliases: [yt]

permissions:
  youtube.*:
    default: op
    children:
      youtube.cmd: true
      youtube.reload: true